# Read from the Existing HDF5 file 

In [1]:
import numpy as np
import h5py
import os.path

In [2]:
#a = h5py.File("SystemEnergies.hdf5", "r+")
b = h5py.File("SystemEnergies.hdf5", "r+")

In [3]:
for name in a:
    print name

NameError: name 'a' is not defined

In [4]:
for name in b:
    print name

AgCu
AlCo
AlFe
AlMg
AlNi
AlPb
AlSm
AlTi
CFe
CoNi
CuZr
FeNi
FeP
FeV
HPd
NiNb
NiZr


In [25]:
arg1 = "AlSm"
grp = a.create_group("%s"%(arg1))
structSet = grp.create_dataset("StructInfo", data=b["%s/StructInfo"%(arg1)][()])
zSet = grp.create_dataset("Z", data=b["%s/Z"%(arg1)][()])
posSet = grp.create_dataset("Position", data=b["%s/Position"%(arg1)][()])
vecSet = grp.create_dataset("BasisVector", data=b["%s/BasisVector"%(arg1)][()])
eneSet = grp.create_dataset("TotAtomEnergy", data=b["%s/TotAtomEnergy"%(arg1)][()])
enthSet = grp.create_dataset("TotAtomEnthalpy", data=b["%s/TotAtomEnthalpy"%(arg1)][()])
concSet = grp.create_dataset("Concentration", data=b["%s/Concentration"%(arg1)][()])
#a.close()

In [26]:
a.close()
b.close()

In [38]:
del a["NiNb"]

In [8]:
b["AlCo/StructInfo"][()]

array(['fcc/vasp.3498', 'fcc/vasp.28', 'fcc/vasp.5970', ...,
       'hcp/vasp.4050', 'hcp/vasp.3415', 'hcp/vasp.5529'],
      dtype='|S32')

In [28]:
a["AlMg/StructInfo"][()]

array(['fcc/vasp.2889', 'fcc/vasp.1817', 'fcc/vasp.6299', ...,
       'hcp/vasp.3283', 'hcp/vasp.3415', 'hcp/vasp.5529'],
      dtype='|S32')

In [12]:
def printname(name):
    print name
a.visit(printname)

AgCu
AgCu/BasisVector
AgCu/Concentration
AgCu/Position
AgCu/StructInfo
AgCu/TotAtomEnergy
AgCu/TotAtomEnthalpy
AgCu/Z
AlCo
AlCo/BasisVector
AlCo/Concentration
AlCo/Position
AlCo/StructInfo
AlCo/TotAtomEnergy
AlCo/TotAtomEnthalpy
AlCo/Z
AlNi
AlNi/BasisVector
AlNi/Concentration
AlNi/Position
AlNi/StructInfo
AlNi/TotAtomEnergy
AlNi/TotAtomEnthalpy
AlNi/Z
AlPb
AlPb/BasisVector
AlPb/Concentration
AlPb/Position
AlPb/StructInfo
AlPb/TotAtomEnergy
AlPb/TotAtomEnthalpy
AlPb/Z
AlTi
AlTi/BasisVector
AlTi/Concentration
AlTi/Position
AlTi/StructInfo
AlTi/TotAtomEnergy
AlTi/TotAtomEnthalpy
AlTi/Z
CuFe
CuFe/BasisVector
CuFe/Concentration
CuFe/Position
CuFe/StructInfo
CuFe/TotAtomEnergy
CuFe/TotAtomEnthalpy
CuFe/Z
CuPb
CuPb/BasisVector
CuPb/Concentration
CuPb/Position
CuPb/StructInfo
CuPb/TotAtomEnergy
CuPb/TotAtomEnthalpy
CuPb/Z
HPd
HPd/BasisVector
HPd/Concentration
HPd/Position
HPd/StructInfo
HPd/TotAtomEnergy
HPd/TotAtomEnthalpy
HPd/Z


In [9]:
a["AlTi/Concentration"][()]

NameError: name 'a' is not defined

In [10]:
b["AlTi/Position"][]

array([  0.        ,   0.        ,   0.        , ...,   0.        ,
        10.10362957,   2.85773804])

In [55]:
f["AlTi/StructInfo"][()]

array(['fcc/vasp.2889', 'fcc/vasp.1817', 'fcc/vasp.5296', ...,
       'hcp/vasp.2949', 'hcp/vasp.5597', 'hcp/vasp.5529'],
      dtype='|S32')

In [53]:
f["AlTi/TotAtomEnergy"][()]

array([-3.05899238, -3.01001553, -3.07878366, ..., -1.1282434 ,
       -1.15871327, -1.16313868])

In [54]:
f["AlTi/TotAtomEnthalpy"][()]

array([ 0.10460392,  0.11594921,  0.11617228, ...,  2.1242052 ,
        2.15122798,  2.14680258])

In [57]:
f["AlTi/Z"][()]

array([ 47.,  47.,  47., ...,  29.,  29.,  29.])

In [21]:
a.close()